### ISSUE TITLE
golang性能分析工具 | 熠熙轻雷

### ISSUE THREAD

**Issue by Devying** [Devying/devying.github.io#4]
https://devying.github.io/2019/11/09/golang%E6%80%A7%E8%83%BD%E5%88%86%E6%9E%90%E5%B7%A5%E5%85%B7/ 

 pprof介绍pprof 类似于php的xhprof，在代码运行期间进行CPU、内存等指标采样，拿到采样数据后可以进行分析，还可以绘制成可视化的图，方便排查性能瓶颈。在go语言中使用的是官方提供的两个包runtime/pprof和net/http/pprof，分别用在脚本方式运行的程序和http server方式运行的程序中。 功能 CPU Profiling：CPU 分析，按照一定的频率采集所监

**Comment by aqcode** [comment]
作者你好能讲一下 这个pprof 出来的图的含义吗
🤝💕
